name: Run Storage tests

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  localstack:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: s3
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        ports:
          - 4566:4566

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Set environment variables for LocalStack
        run: |
          echo "AWS_ACCESS_KEY_ID=test" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=test" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ENDPOINT_URL=http://localhost:4566" >> $GITHUB_ENV

      - name: Create S3 bucket in LocalStack
        run: |
          aws --endpoint-url=http://localhost:4566 s3 mb s3://test-fuzz-bucket

      - name: Run Go program
        run: |
          go run main.go

      - name: Check that corpus.zip is present in S3
        run: |
          aws --endpoint-url=http://localhost:4566 s3 ls s3://test-fuzz-bucket/corpus.zip || {
            echo "❌ corpus.zip not found in S3 bucket."
            exit 1
          }

      - name: Check that corpus directory exists locally
        run: |
          if [ ! -d "./corpus" ]; then
            echo "❌ Local 'corpus' directory not found."
            exit 1
          else
            echo "✅ Local 'corpus' directory exists."
          fi
