name: E2E Tests

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to test"
        required: true

jobs:
  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.GITHUB_TOKEN }}
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: s3
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        ports:
          - 4566:4566

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Set environment variables for LocalStack
        run: |
          echo "AWS_ACCESS_KEY_ID=test" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=test" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ENDPOINT_URL=http://localhost:4566" >> $GITHUB_ENV

      - name: Create S3 bucket in LocalStack
        run: |
          aws --endpoint-url=http://localhost:4566 s3 mb s3://test-fuzz-bucket

      - name: Download seed_corpus into ~/corpus
        run: |
          mkdir -p "$HOME/corpus"
          curl -L \
            https://codeload.github.com/NishantBansal2003/go-fuzzing-example/tar.gz/fuzz-example \
            | tar -xz \
              --strip-components=2 \
              -C "$HOME/corpus" \
              go-fuzzing-example-fuzz-example/seed_corpus

      - name: Zip the corpus directory into corpus.zip
        run: |
          cd "$HOME"
          zip -r corpus.zip corpus

      - name: Upload corpus.zip to LocalStack S3
        run: |
          aws --endpoint-url=http://localhost:4566 s3 cp "$HOME/corpus.zip" s3://test-fuzz-bucket/corpus.zip

      - name: Set up Go
        id: setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.9"

      - name: Install dependencies
        run: go mod download

      - name: Run E2E tests
        run: make e2e-test
